package model;
// Generated 08-jul-2020 21:20:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bodega generated by hbm2java
 */
public class Bodega  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     

    public Bodega() {
    }

	
    public Bodega(String nombre) {
        this.nombre = nombre;
    }

    public Bodega(Integer id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
  
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
   




}


