package model;
// Generated 08-jul-2020 21:20:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Caja generated by hbm2java
 */
public class Caja  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private Set stocks = new HashSet(0);

    public Caja() {
    }

	
    public Caja(String nombre) {
        this.nombre = nombre;
    }
    public Caja(String nombre, String descripcion, Set stocks) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.stocks = stocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


