package model;
// Generated 08-jul-2020 21:20:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private Marca marca;
     private Subcategoria subcategoria;
     private String nombre;
     private String codigo;
     private String modelo;
     private String descripcion;
     private byte[] foto;
     private Set stocks = new HashSet(0);

    public Item() {
    }

	
    public Item(Categoria categoria, Marca marca, Subcategoria subcategoria, String nombre, String codigo, String modelo) {
        this.categoria = categoria;
        this.marca = marca;
        this.subcategoria = subcategoria;
        this.nombre = nombre;
        this.codigo = codigo;
        this.modelo = modelo;
    }
    public Item(Categoria categoria, Marca marca, Subcategoria subcategoria, String nombre, String codigo, String modelo, String descripcion, byte[] foto, Set stocks) {
       this.categoria = categoria;
       this.marca = marca;
       this.subcategoria = subcategoria;
       this.nombre = nombre;
       this.codigo = codigo;
       this.modelo = modelo;
       this.descripcion = descripcion;
       this.foto = foto;
       this.stocks = stocks;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set stocks) {
        this.stocks = stocks;
    }




}


