package model;
// Generated 08-jul-2020 21:20:38 by Hibernate Tools 4.3.1


/**
 * Stock generated by hbm2java
 */
public class Stock  implements java.io.Serializable {


     private int id;
     private int bodega;
     private int caja;
     private int item;
     private int lote;
     private String fechaIngreso;
     private int cantidad;

    public Stock() {
    }

    public Stock(int id, int bodega, int caja, int item, int lote, int unidad, String fechaIngreso, int cantidad) {
        this.id = id;
        this.bodega = bodega;
        this.caja = caja;
        this.item = item;
        this.lote = lote;
        this.fechaIngreso = fechaIngreso;
        this.cantidad = cantidad;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getBodega() {
        return bodega;
    }

    public void setBodega(int bodega) {
        this.bodega = bodega;
    }

    public int getCaja() {
        return caja;
    }

    public void setCaja(int caja) {
        this.caja = caja;
    }

    public int getItem() {
        return item;
    }

    public void setItem(int item) {
        this.item = item;
    }

    public int getLote() {
        return lote;
    }

    public void setLote(int lote) {
        this.lote = lote;
    }

  
    public String getFechaIngreso() {
        return fechaIngreso;
    }

    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }

    public double getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

   


}


