package model;
// Generated 08-jul-2020 21:20:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer id;
     private String subcategoria;
     private Set items = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(String subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Subcategoria(String subcategoria, Set items) {
       this.subcategoria = subcategoria;
       this.items = items;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(String subcategoria) {
        this.subcategoria = subcategoria;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


